### ISSUE TITLE
consider using a single CSI to provide services for all alluxio clusters

### ISSUE THREAD

**Issue by wwq2333** [Alluxio/k8s-operator#28]
In order to facilitate management, we are currently building a set of alluxio for a dataset.  When trying the operator, we found that each alluxio cluster has an independent CSI;  Although the resource overhead of a single CSI is not high, considering a large-scale training cluster, it is very common to use hundreds of datasets at the same time.  Since node-plugin needs to be deployed on every machine, the cumulative resource consumption is terrible. Therefore, we can consider using a single CSI to provide services for all alluxio clusters;

**Comment by ssz1997** [comment]
Fixed in #29
