### ISSUE TITLE
[Question] Why I see nothing about job-master or job-worker

### ISSUE THREAD

**Issue by lucaspeng12138** [Alluxio/k8s-operator#81]
Are they no longer needed? I find `entrypoint.sh` still has master-only and master options, master pod only start master process w/o job-master

**Comment by lucaspeng12138** [comment]
@ssz1997 could you please help me out? Is latest images far more different from 2.9.3?

**Comment by ssz1997** [comment]
@lucaspeng12138 Hi. The operator is designed for Alluxio 3xx, which is an almost completely new architecture from Alluxio 2.x. Here's some related docs about this new architecture Dora: https://docs.alluxio.io/os/user/edge/en/introduction/Introduction.html#dora-architecture, https://docs.alluxio.io/os/user/edge/en/core-services/Data-Caching.html#dora-cache-overview.

And to answer your question, we got rid of the job service in 3xx, including job master and job worker. The `entrypoint.sh` just hasn't been updated yet.
